name: Build

on:
  push:
    branches: [main, develop, VS2022]
  pull_request:
    branches: [main, develop, VS2022]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: KeePass.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    name: 'Build // ${{ matrix.configuration }}'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore Packages
      run: dotnet restore

    - name: Build
      run: dotnet build
